[platformio]
default_envs = d1_mini

[env]
platform = espressif8266
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit NeoPixel@^1.12.0

[env:d1_mini]
board = d1_mini
upload_protocol = esptool
upload_speed = 921600

[env:esp01_1m_serial]
board = esp01_1m
board_build.flash_mode = dout
upload_protocol = esptool
upload_speed = 115200

[env:esp01_1m_ota]
board = esp01_1m
board_build.flash_mode = dout
upload_protocol = espota
; Connect your computer to the ESP8266-NeoPixel AP before uploading.
upload_port = 192.168.4.1
; If using OTA password:
; upload_flags =
;     --auth=YOUR_OTA_PASSWORD
